export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT= 'LOGOUT';
export const GET_TRAININGS = ' GET_TRAININGS';
export const TRAINING_ERROR = 'TRAINING_ERROR';
export const DELETE_TRAINING = 'DELETE_TRAINING';
export const ADD_TRAINING = 'ADD_TRAINING';
export const UPDATE_TRAINING = 'UPDATE_TRAINING';
export const GET_TRAINING = 'GET_TRAINING';
export const GET_INTERNSHIPS ='GET_INTERNSHIPS';
export const   INTERNSHIP_ERROR= 'INTERNSHIP_ERROR';
export const DELETE_INTERNSHIP = 'DELETE_INTERNSHIP';
export const   ADD_INTERNSHIP = 'ADD_INTERNSHIP';
export const   UPDATE_INTERNSHIP = 'UPDATE_INTERNSHIP';
export const   GET_INTERNSHIP = 'GET_INTERNSHIP';
export const GET_COMPANIES ='GET_COMPANIES';
export const COMPANY_ERROR = 'COMPANY_ERROR';
export const VERIFY_COMPANY ='VERIFY_COMPANY';
export const GET_PROFILES='GET_PROFILES';
export const PROFILE_ERROR='PROFILE_ERROR';
export const BLOCK_PROFILE ='BLOCK_PROFILE';
export const UNBLOCK_PROFILE='UNBLOCK_PROFILE';
export const GET_EVENTS = 'GET_EVENTS';
 export const EVENT_ERROR = 'EVENT_ERROR';
 export const DELETE_EVENT = 'DELETE_EVENT';
 export const ADD_EVENT = 'ADD_EVENT';
 export const UPDATE_EVENT = 'UPDATE_EVENT';
 export const GET_EVENT = 'GET_EVENT';


 